// Generated by scripts/regrid-data.mjs — do not edit by hand.
import type { EnrichedEntry } from '../../../../types.js';

export const ENTRIES: readonly EnrichedEntry[] = [
  {
    id: 'en-disappointment-1rsljbg',
    word: 'DISAPPOINTMENT',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['DIS', 'AP', 'POINT', 'MENT'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Sadness arising from unfulfilled hopes or expectations',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Letdown',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'To his _____, the concert was canceled at the last minute.',
      },
    ],
  },
  {
    id: 'en-rehabilitation-ex65vs',
    word: 'REHABILITATION',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['RE', 'HA', 'BIL', 'I', 'TA', 'TION'],
    clues: [
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Recovery',
      },
      {
        type: 'definition',
        difficulty: 3,
        text: 'The process of restoring someone to health or a normal life',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'After the injury, months of _____ helped her walk again.',
      },
    ],
  },
  {
    id: 'en-characteristic-1ay53bw',
    word: 'CHARACTERISTIC',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['CHAR', 'AC', 'TER', 'IS', 'TIC'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'A distinguishing quality or feature of someone or something',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Trait',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Generosity was a defining _____ of her personality.',
      },
    ],
  },
  {
    id: 'en-superintendent-lxox73',
    word: 'SUPERINTENDENT',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['SU', 'PER', 'IN', 'TEN', 'DENT'],
    clues: [
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Supervisor',
      },
      {
        type: 'definition',
        difficulty: 3,
        text: 'A person who oversees an organization, department, or building',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: "The building's _____ came up to fix the broken boiler.",
      },
    ],
  },
  {
    id: 'en-reconstruction-16m779p',
    word: 'RECONSTRUCTION',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['RE', 'CON', 'STRUC', 'TION'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'The act of building again or restoring something to its former state',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Rebuilding',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The _____ of the bridge took two years after the flood.',
      },
    ],
  },
  {
    id: 'en-specifications-17wsl6r',
    word: 'SPECIFICATIONS',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['SPEC', 'I', 'FI', 'CA', 'TIONS'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Detailed descriptions of the required design or standards for something',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Requirements',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The engineers built the bridge to exact _____.',
      },
    ],
  },
  {
    id: 'en-accountability-avxkoa',
    word: 'ACCOUNTABILITY',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['AC', 'COUNT', 'ABIL', 'ITY'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: "The obligation to answer for one's actions and decisions",
      },
      {
        type: 'synonym',
        difficulty: 2,
        text: 'Responsibility',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Voters demanded greater _____ from their leaders.',
      },
    ],
  },
  {
    id: 'en-pharmaceutical-11zl8v0',
    word: 'PHARMACEUTICAL',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'adjective',
    syllables: ['PHAR', 'MA', 'CEU', 'TI', 'CAL'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Relating to medicinal drugs or their manufacture',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Medicinal',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The new drug passed every _____ trial before hitting the market.',
      },
    ],
  },
  {
    id: 'en-qualifications-n9xe0b',
    word: 'QUALIFICATIONS',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['QUAL', 'I', 'FI', 'CA', 'TIONS'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'The credentials and skills listed on a résumé',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Credentials',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'Please list your _____ on the application form',
      },
    ],
  },
  {
    id: 'en-administrators-1rjy08r',
    word: 'ADMINISTRATORS',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['AD', 'MIN', 'IS', 'TRA', 'TORS'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: "People who manage an organization's affairs",
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Managers',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'School _____ set the yearly budget',
      },
    ],
  },
  {
    id: 'en-correspondence-1lex8mz',
    word: 'CORRESPONDENCE',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['COR', 'RE', 'SPON', 'DENCE'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Letters and messages exchanged between people',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Communication',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'She kept all their _____ in a wooden box',
      },
    ],
  },
  {
    id: 'en-establishments-81gh61',
    word: 'ESTABLISHMENTS',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['ES', 'TAB', 'LISH', 'MENTS'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Businesses or institutions such as shops and firms',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Institutions',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Licensed _____ must close by midnight',
      },
    ],
  },
  {
    id: 'en-organizational-176ss07',
    word: 'ORGANIZATIONAL',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'adjective',
    syllables: ['OR', 'GA', 'NI', 'ZA', 'TIONAL'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Relating to the structure or running of a group',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Structural',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The merger caused major _____ changes',
      },
    ],
  },
  {
    id: 'en-demonstrations-1m2quj1',
    word: 'DEMONSTRATIONS',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['DEMON', 'STRA', 'TIONS'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Public gatherings expressing protest or support',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Protests',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'Cooking _____ showed the audience how to prepare the dish.',
      },
    ],
  },
  {
    id: 'en-sustainability-1edqe1s',
    word: 'SUSTAINABILITY',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['SUS', 'TAIN', 'ABIL', 'ITY'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'The ability to be kept at a steady level without depleting resources',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Viability',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: "The company's _____ goals focus on cutting carbon emissions.",
      },
    ],
  },
  {
    id: 'en-concentrations-k5npb3',
    word: 'CONCENTRATIONS',
    lang: 'en',
    freqTier: 2,
    length: 14,
    pos: 'noun',
    syllables: ['CON', 'CEN', 'TRA', 'TIONS'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'The relative amounts of a substance in a mixture',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Densities',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'High _____ of salt made the water undrinkable.',
      },
    ],
  },
];
