// Generated by scripts/regrid-data.mjs — do not edit by hand.
import type { EnrichedEntry } from '../../../../types.js';

export const ENTRIES: readonly EnrichedEntry[] = [
  {
    id: 'en-administration-1o1pcsv',
    word: 'ADMINISTRATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['AD', 'MIN', 'IS', 'TRA', 'TION'],
    clues: [
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Management',
      },
      {
        type: 'definition',
        difficulty: 3,
        text: 'The running of an organization or government',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The new _____ promised to lower taxes.',
      },
    ],
  },
  {
    id: 'en-responsibility-17w6yqj',
    word: 'RESPONSIBILITY',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['RE', 'SPON', 'SI', 'BIL', 'ITY'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'A duty or task one is expected to handle',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Obligation',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Managing the budget is now her _____.',
      },
    ],
  },
  {
    id: 'en-communications-13s8rxs',
    word: 'COMMUNICATIONS',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['COM', 'MU', 'NI', 'CA', 'TIONS'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'The means of sending and receiving information',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Correspondence',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The storm knocked out all _____ to the island.',
      },
    ],
  },
  {
    id: 'en-representative-48yypw',
    word: 'REPRESENTATIVE',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['REP', 'RE', 'SEN', 'TA', 'TIVE'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'A person chosen to act or speak on behalf of others',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Delegate',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'She is the elected _____ for our district.',
      },
    ],
  },
  {
    id: 'en-transportation-kwqrkz',
    word: 'TRANSPORTATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['TRANS', 'PORTA', 'TION'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'The means or system of moving people or goods from place to place',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Conveyance',
      },
      {
        type: 'fill-blank',
        difficulty: 1,
        text: 'Public _____ includes buses and trains.',
      },
    ],
  },
  {
    id: 'en-infrastructure-14arqmm',
    word: 'INFRASTRUCTURE',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['IN', 'FRA', 'STRUC', 'TURE'],
    clues: [
      {
        type: 'definition',
        difficulty: 4,
        text: 'The basic physical systems of a society, like roads and power',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Framework',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The city spent billions on new _____ such as bridges and rail.',
      },
    ],
  },
  {
    id: 'en-administrative-1c1szof',
    word: 'ADMINISTRATIVE',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'adjective',
    syllables: ['AD', 'MIN', 'IS', 'TRA', 'TIVE'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Relating to the running or management of an organization',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Managerial',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'She handled all the _____ paperwork for the office.',
      },
    ],
  },
  {
    id: 'en-representation-b5ufyo',
    word: 'REPRESENTATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['REP', 'RE', 'SEN', 'TA', 'TION'],
    clues: [
      {
        type: 'definition',
        difficulty: 4,
        text: 'The act of standing in for or depicting something',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Depiction',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Citizens demanded fair _____ in the new parliament.',
      },
    ],
  },
  {
    id: 'en-constitutional-39ngy3',
    word: 'CONSTITUTIONAL',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'adjective',
    syllables: ['CON', 'STI', 'TU', 'TIONAL'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: "In accordance with a country's basic governing principles",
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Lawful',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The court ruled that the new law was fully _____.',
      },
    ],
  },
  {
    id: 'en-discrimination-1a1ie0',
    word: 'DISCRIMINATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['DIS', 'CRIM', 'I', 'NA', 'TION'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Unjust treatment of people based on their group or category',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Prejudice',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'New laws were introduced to combat workplace _____.',
      },
    ],
  },
  {
    id: 'en-implementation-rg5813',
    word: 'IMPLEMENTATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['IM', 'PLE', 'MEN', 'TA', 'TION'],
    clues: [
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'The _____ of the new policy took several months.',
      },
      {
        type: 'definition',
        difficulty: 3,
        text: 'The act of putting a plan or decision into effect',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Execution',
      },
    ],
  },
  {
    id: 'en-interpretation-n1t017',
    word: 'INTERPRETATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['IN', 'TER', 'PRE', 'TA', 'TION'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'An explanation of the meaning of something',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Explanation',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: "Her _____ of the poem differed sharply from the teacher's.",
      },
    ],
  },
  {
    id: 'en-investigations-idy9mm',
    word: 'INVESTIGATIONS',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['IN', 'VES', 'TI', 'GA', 'TIONS'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Formal inquiries into facts or alleged crimes',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Inquiries',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'Detectives opened two separate _____ into the theft.',
      },
    ],
  },
  {
    id: 'en-transformation-gk8vhs',
    word: 'TRANSFORMATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['TRANS', 'FOR', 'MA', 'TION'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'A thorough or dramatic change in form or appearance',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Metamorphosis',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The renovation brought about a complete _____ of the old building.',
      },
    ],
  },
  {
    id: 'en-classification-17ckkn5',
    word: 'CLASSIFICATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['CLAS', 'SI', 'FI', 'CA', 'TION'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'The act of arranging things into categories or groups',
      },
      {
        type: 'synonym',
        difficulty: 2,
        text: 'Categorization',
      },
      {
        type: 'fill-blank',
        difficulty: 4,
        text: 'Biologists debated the correct _____ of the newly found species.',
      },
    ],
  },
  {
    id: 'en-identification-1snguor',
    word: 'IDENTIFICATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['IDEN', 'TI', 'FI', 'CA', 'TION'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Official proof of who you are, often a card',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Recognition',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Guards asked every visitor to show _____ at the door.',
      },
    ],
  },
  {
    id: 'en-simultaneously-1cw249f',
    word: 'SIMULTANEOUSLY',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'adverb',
    syllables: ['SI', 'MUL', 'TA', 'NE', 'OUSLY'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Happening at exactly the same time',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Concurrently',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'The choir and orchestra began _____, in perfect time.',
      },
    ],
  },
  {
    id: 'en-recommendation-1ugv65q',
    word: 'RECOMMENDATION',
    lang: 'en',
    freqTier: 1,
    length: 14,
    pos: 'noun',
    syllables: ['REC', 'OM', 'MEN', 'DA', 'TION'],
    clues: [
      {
        type: 'synonym',
        difficulty: 2,
        text: 'Suggestion',
      },
      {
        type: 'definition',
        difficulty: 3,
        text: 'A proposal as to the best course of action',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: "I bought the novel on a friend's _____.",
      },
    ],
  },
];
