// Generated by scripts/regrid-data.mjs — do not edit by hand.
import type { EnrichedEntry } from '../../../../types.js';

export const ENTRIES: readonly EnrichedEntry[] = [
  {
    id: 'en-electromagnetic-176kzq1',
    word: 'ELECTROMAGNETIC',
    lang: 'en',
    freqTier: 3,
    length: 15,
    pos: 'adjective',
    syllables: ['ELEC', 'TRO', 'MAG', 'NETIC'],
    clues: [
      {
        type: 'definition',
        difficulty: 4,
        text: 'Of or relating to the spectrum that includes light, radio, and X-rays',
      },
      {
        type: 'fill-blank',
        difficulty: 4,
        text: 'Radio waves and visible light are both forms of _____ radiation.',
      },
    ],
  },
  {
    id: 'en-differentiation-4p5ray',
    word: 'DIFFERENTIATION',
    lang: 'en',
    freqTier: 3,
    length: 15,
    pos: 'noun',
    syllables: ['DIF', 'FER', 'EN', 'TI', 'A', 'TION'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'The act of distinguishing one thing from another',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Distinction',
      },
      {
        type: 'fill-blank',
        difficulty: 4,
        text: 'Product _____ helps a brand stand out from its rivals.',
      },
    ],
  },
  {
    id: 'en-notwithstanding-uyzksm',
    word: 'NOTWITHSTANDING',
    lang: 'en',
    freqTier: 3,
    length: 15,
    pos: 'other',
    syllables: ['NOTWITH', 'STAND', 'ING'],
    clues: [
      {
        type: 'definition',
        difficulty: 4,
        text: 'In spite of; despite',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Nevertheless',
      },
      {
        type: 'fill-blank',
        difficulty: 4,
        text: '_____ the heavy rain, the match continued as planned.',
      },
    ],
  },
];
