// Generated by scripts/regrid-data.mjs — do not edit by hand.
import type { EnrichedEntry } from '../../../../types.js';

export const ENTRIES: readonly EnrichedEntry[] = [
  {
    id: 'en-internationally-1hsl5m4',
    word: 'INTERNATIONALLY',
    lang: 'en',
    freqTier: 2,
    length: 15,
    pos: 'adverb',
    syllables: ['IN', 'TER', 'NA', 'TION', 'ALLY'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'In a way involving two or more countries',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Globally',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The band became famous _____ after the tour.',
      },
    ],
  },
  {
    id: 'en-straightforward-9bkkt0',
    word: 'STRAIGHTFORWARD',
    lang: 'en',
    freqTier: 2,
    length: 15,
    pos: 'adjective',
    syllables: ['STRAIGHT', 'FOR', 'WARD'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Easy to do or understand; uncomplicated',
      },
      {
        type: 'synonym',
        difficulty: 2,
        text: 'Uncomplicated',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The instructions were so _____ that we finished in minutes.',
      },
    ],
  },
  {
    id: 'en-accomplishments-t5isgj',
    word: 'ACCOMPLISHMENTS',
    lang: 'en',
    freqTier: 2,
    length: 15,
    pos: 'noun',
    syllables: ['AC', 'COM', 'PLISH', 'MENTS'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Things achieved successfully through effort',
      },
      {
        type: 'synonym',
        difficulty: 2,
        text: 'Achievements',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Winning the award was one of her greatest _____.',
      },
    ],
  },
  {
    id: 'en-representations-obncu1',
    word: 'REPRESENTATIONS',
    lang: 'en',
    freqTier: 2,
    length: 15,
    pos: 'noun',
    syllables: ['REP', 'RE', 'SEN', 'TA', 'TIONS'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Depictions or portrayals of something',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Depictions',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'The museum displayed artistic _____ of ancient battles.',
      },
    ],
  },
  {
    id: 'en-interpretations-1yqd25k',
    word: 'INTERPRETATIONS',
    lang: 'en',
    freqTier: 2,
    length: 15,
    pos: 'noun',
    syllables: ['IN', 'TER', 'PRE', 'TA', 'TIONS'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Explanations of the meaning of something',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Readings',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Different _____ of the poem sparked a lively debate.',
      },
    ],
  },
];
