// Generated by scripts/regrid-data.mjs — do not edit by hand.
import type { EnrichedEntry } from '../../../../types.js';

export const ENTRIES: readonly EnrichedEntry[] = [
  {
    id: 'en-representatives-e2fm7p',
    word: 'REPRESENTATIVES',
    lang: 'en',
    freqTier: 1,
    length: 15,
    pos: 'noun',
    syllables: ['REP', 'RE', 'SEN', 'TA', 'TIVES'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'People chosen to act or speak on behalf of others',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Delegates',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'The House of _____ voted to pass the new bill.',
      },
    ],
  },
  {
    id: 'en-congratulations-wlzed0',
    word: 'CONGRATULATIONS',
    lang: 'en',
    freqTier: 1,
    length: 15,
    pos: 'other',
    syllables: ['CON', 'GRAT', 'U', 'LA', 'TIONS'],
    clues: [
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Felicitations',
      },
      {
        type: 'definition',
        difficulty: 2,
        text: 'An expression of praise for an achievement or good fortune',
      },
      {
        type: 'fill-blank',
        difficulty: 1,
        text: '_____ on your graduation!',
      },
    ],
  },
  {
    id: 'en-recommendations-1olc3gn',
    word: 'RECOMMENDATIONS',
    lang: 'en',
    freqTier: 1,
    length: 15,
    pos: 'noun',
    syllables: ['REC', 'OM', 'MEN', 'DA', 'TIONS'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Suggestions offered as worthy of acceptance',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Endorsements',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'The doctor made several _____ for improving his diet.',
      },
    ],
  },
  {
    id: 'en-characteristics-1bw61r1',
    word: 'CHARACTERISTICS',
    lang: 'en',
    freqTier: 1,
    length: 15,
    pos: 'noun',
    syllables: ['CHAR', 'AC', 'TER', 'IS', 'TICS'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Distinguishing qualities or features of something',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Traits',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'Each breed has its own physical _____.',
      },
    ],
  },
];
