// Generated by scripts/regrid-data.mjs — do not edit by hand.
import type { EnrichedEntry } from '../../../../types.js';

export const ENTRIES: readonly EnrichedEntry[] = [
  {
    id: 'de-ausgezeichneten-v2tg85',
    word: 'AUSGEZEICHNETEN',
    lang: 'de',
    freqTier: 3,
    length: 15,
    pos: 'adjective',
    syllables: ['AUS', 'GE', 'ZEICH', 'NE', 'TEN'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'In hervorragender, sehr guter Qualität',
      },
      {
        type: 'synonym',
        difficulty: 1,
        text: 'exzellenten',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Die Jury lobte die Arbeit der _____ Studenten.',
      },
    ],
  },
  {
    id: 'de-intellektuellen-99keiy',
    word: 'INTELLEKTUELLEN',
    lang: 'de',
    freqTier: 3,
    length: 15,
    pos: 'noun',
    syllables: ['IN', 'TEL', 'LEK', 'TU', 'EL', 'LEN'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Gebildete Menschen, die sich geistig-wissenschaftlich mit einer Sache auseinandersetzen',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Gebildeten',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Die Regierung geriet in Konflikt mit den kritischen _____ des Landes.',
      },
    ],
  },
  {
    id: 'de-marktwirtschaft-clw0z9',
    word: 'MARKTWIRTSCHAFT',
    lang: 'de',
    freqTier: 3,
    length: 15,
    pos: 'noun',
    syllables: ['MARKT', 'WIRT', 'SCHAFT'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Wirtschaftsordnung, in der Angebot und Nachfrage die Preise bestimmen',
      },
      {
        type: 'synonym',
        difficulty: 4,
        text: 'Kapitalismus',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'In einer freien _____ regelt der Wettbewerb das Angebot.',
      },
    ],
  },
  {
    id: 'de-rechtschreibung-1gndtz9',
    word: 'RECHTSCHREIBUNG',
    lang: 'de',
    freqTier: 3,
    length: 15,
    pos: 'noun',
    syllables: ['RECHT', 'SCHREI', 'BUNG'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Regeln für das korrekte Verfassen von Wörtern in einer Sprache',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Orthografie',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'Der Aufsatz war voller Fehler in der _____.',
      },
    ],
  },
  {
    id: 'de-selbstvertrauen-5ls2fu',
    word: 'SELBSTVERTRAUEN',
    lang: 'de',
    freqTier: 3,
    length: 15,
    pos: 'noun',
    syllables: ['SELBST', 'VER', 'TRAU', 'EN'],
    clues: [
      {
        type: 'definition',
        difficulty: 2,
        text: 'Der feste Glaube an die eigenen Fähigkeiten und den eigenen Wert',
      },
      {
        type: 'synonym',
        difficulty: 3,
        text: 'Zuversicht',
      },
      {
        type: 'fill-blank',
        difficulty: 2,
        text: 'Nach dem Erfolg strotzte sie nur so vor _____.',
      },
    ],
  },
  {
    id: 'de-ausschreitungen-55k3op',
    word: 'AUSSCHREITUNGEN',
    lang: 'de',
    freqTier: 3,
    length: 15,
    pos: 'noun',
    syllables: ['AUS', 'SCHREI', 'TUN', 'GEN'],
    clues: [
      {
        type: 'definition',
        difficulty: 3,
        text: 'Gewalttätige Zusammenstöße und Krawalle bei Demonstrationen oder Massenveranstaltungen',
      },
      {
        type: 'synonym',
        difficulty: 2,
        text: 'Krawalle',
      },
      {
        type: 'fill-blank',
        difficulty: 3,
        text: 'Nach dem Spiel kam es rund um das Stadion zu schweren _____.',
      },
    ],
  },
];
