// scripts/regrid-data.mjs
// One-shot: convert the flat base/tier-N.ts + enriched/len-N.ts layout into the
// length×tier grid. Reads the *compiled* ESM data (built from the old layout), so
// build `esm/` before running this. Inert after the old files are deleted.
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { bucketByLength, bucketByTier } from './regrid-lib.mjs';

const DATA = join('src', 'data');
const langs = ['en', 'de'];
const TIERS = [1, 2, 3, 4, 5];
const LENS = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];

// Extract base words from a flat tier .ts in file order. Word literals are the only
// single-quoted tokens in these files; [^'] captures accented chars (ÄÖÜẞ) too.
function readBaseTier(lang, tier) {
  const txt = readFileSync(join(DATA, lang, 'base', `tier-${tier}.ts`), 'utf8');
  return [...txt.matchAll(/'([^']*)'/g)].map((m) => m[1]);
}

function emitBase(lang, len, tier, words) {
  const dir = join(DATA, lang, 'base', `len-${len}`);
  mkdirSync(dir, { recursive: true });
  const body =
    `// Generated by scripts/regrid-data.mjs — do not edit by hand.\n` +
    `// ${lang} base words, length ${len}, freqTier ${tier} (frequency order preserved).\n` +
    `export const WORDS: readonly string[] = [\n${words.map((w) => `  '${w}',`).join('\n')}\n];\n`;
  writeFileSync(join(dir, `tier-${tier}.ts`), body);
}

function emitEnriched(lang, len, tier, entries) {
  const dir = join(DATA, lang, 'enriched', `len-${len}`);
  mkdirSync(dir, { recursive: true });
  const body =
    `// Generated by scripts/regrid-data.mjs — do not edit by hand.\n` +
    `import type { EnrichedEntry } from '../../../../types.js';\n\n` +
    `export const ENTRIES: readonly EnrichedEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
  writeFileSync(join(dir, `tier-${tier}.ts`), body);
}

for (const lang of langs) {
  // BASE: concat all tiers in order, bucket per (len,tier) preserving order.
  for (let tier of TIERS) {
    const byLen = bucketByLength(readBaseTier(lang, tier));
    for (const [len, words] of byLen) emitBase(lang, len, tier, words);
  }
  // ENRICHED: read compiled ESM entries per length, bucket by freqTier.
  for (const len of LENS) {
    const mod = await import(new URL(`../esm/data/${lang}/enriched/len-${len}.js`, import.meta.url));
    const byTier = bucketByTier(mod.ENTRIES);
    for (const [tier, entries] of byTier) emitEnriched(lang, len, tier, entries);
  }
  // Delete the old flat files.
  for (const tier of TIERS) rmSync(join(DATA, lang, 'base', `tier-${tier}.ts`), { force: true });
  for (const len of LENS) rmSync(join(DATA, lang, 'enriched', `len-${len}.ts`), { force: true });
}
console.log('Regridded base + enriched into len-<L>/tier-<T> leaves.');
