// Generated by scripts/regrid-data.mjs — do not edit by hand.
// en base words, length 14, freqTier 1 (frequency order preserved).
export const WORDS: readonly string[] = [
  'ADMINISTRATION',
  'RESPONSIBILITY',
  'COMMUNICATIONS',
  'REPRESENTATIVE',
  'TRANSPORTATION',
  'INFRASTRUCTURE',
  'ADMINISTRATIVE',
  'REPRESENTATION',
  'CONSTITUTIONAL',
  'DISCRIMINATION',
  'IMPLEMENTATION',
  'INTERPRETATION',
  'INVESTIGATIONS',
  'TRANSFORMATION',
  'CLASSIFICATION',
  'IDENTIFICATION',
  'SIMULTANEOUSLY',
  'RECOMMENDATION',
];
