// Generated by scripts/regrid-data.mjs — do not edit by hand.
// en base words, length 15, freqTier 3 (frequency order preserved).
export const WORDS: readonly string[] = [
  'ELECTROMAGNETIC',
  'DIFFERENTIATION',
  'NOTWITHSTANDING',
  'PHARMACEUTICALS',
  'EXPERIMENTATION',
  'INSTRUMENTATION',
  'COMPETITIVENESS',
  'CONFIDENTIALITY',
  'ENVIRONMENTALLY',
  'EXTRAORDINARILY',
  'ENTREPRENEURIAL',
  'PROFESSIONALISM',
  'TRANSFORMATIONS',
  'ADMINISTRATIONS',
  'PSYCHOLOGICALLY',
];
