// Generated by scripts/regrid-data.mjs — do not edit by hand.
// en base words, length 15, freqTier 4 (frequency order preserved).
export const WORDS: readonly string[] = [
  'ACKNOWLEDGEMENT',
  'DISSATISFACTION',
  'INTERCHANGEABLE',
  'GLOUCESTERSHIRE',
  'CHARLOTTESVILLE',
  'INCONSISTENCIES',
  'TRANSPLANTATION',
  'VULNERABILITIES',
  'DIVERSIFICATION',
  'REVOLUTIONARIES',
  'UNINTENTIONALLY',
  'IMPLEMENTATIONS',
  'CLASSIFICATIONS',
  'ANTIDEPRESSANTS',
  'UNCONDITIONALLY',
  'TECHNOLOGICALLY',
  'DISAPPOINTMENTS',
];
