// Generated by scripts/regrid-data.mjs — do not edit by hand.
// en base words, length 15, freqTier 2 (frequency order preserved).
export const WORDS: readonly string[] = [
  'INTERNATIONALLY',
  'STRAIGHTFORWARD',
  'ACCOMPLISHMENTS',
  'REPRESENTATIONS',
  'INTERPRETATIONS',
];
